/* Re-runnable browser QA against the guarded copy server, never production. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE);
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const url = process.env.NETEM_COPY_URL || 'http://127.0.0.1:8772';
assert.equal(url, 'http://127.0.0.1:8772');
const output = process.env.NETEM_COPY_OUTPUT;
const shots = process.env.NETEM_QA_SCREENSHOT_DIR;
assert(output && shots && process.env.NETEM_COPY_PASSWORD);
const phase = process.argv[2] || 'exercise';
assert(['exercise', 'restart'].includes(phase));
const results = { url, phase, browser: 'Bundled Playwright / installed Chrome; Browser plugin unavailable', checks: [], screenshots: [] };
const check = (name, value) => { assert(value, name); results.checks.push(name); };
let browser;
(async () => {
  browser = await chromium.launch({ executablePath: process.env.CHROME_EXE, headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => {
    if (['error', 'warning'].includes(message.type()) && !message.text().includes('401 (Unauthorized)')) errors.push(message.text());
  });
  const api = async (endpoint, data, ctx = context) => {
    const response = data === undefined ? await ctx.request.get(url + endpoint) : await ctx.request.post(url + endpoint, { data, headers: { Origin: url } });
    assert(response.ok(), endpoint + ' ' + response.status());
    return response.json();
  };
  const login = async (p, username) => {
    await p.goto(url);
    await p.getByLabel('用户名', { exact: true }).fill(username);
    await p.getByLabel('密码', { exact: true }).fill(process.env.NETEM_COPY_PASSWORD);
    await p.getByRole('button', { name: '登录', exact: true }).click();
    await p.getByRole('link', { name: '我的词库', exact: true }).waitFor();
  };
  const shot = async (p, name) => {
    const file = path.join(shots, 'netem-copy-' + name + '.png');
    await p.screenshot({ path: file, fullPage: false }); results.screenshots.push(file);
  };
  const body = async p => p.locator('body').innerText();
  await login(page, 'netem_copy_private');
  if (phase === 'restart') {
    const saved = JSON.parse(fs.readFileSync(path.join(output, 'browser-exercise.json'), 'utf8')).persistence;
    const selection = await api('/api/lexicons/selection');
    check('private explicit selection survives server restart', selection.lexicon_id === saved.privateLexicon && selection.source === 'explicit');
    const own = await api('/api/words/state/' + saved.privateState);
    const pub = await api('/api/words/state/' + saved.publicState);
    check('private progress survives restart', own.recall_success === saved.privateSuccess);
    check('public progress survives restart independently', pub.recall_success === saved.publicSuccess && pub.status === saved.publicStatus);
    await page.goto(url + '/library/' + saved.publicState);
    await page.getByRole('heading', { name: 'the', exact: true }).waitFor();
    check('source attribution persists after restart', (await body(page)).includes('Karl Bartel'));
  } else {
    const libs = await api('/api/lexicons');
    const privateLibrary = libs.find(x => x.name === 'NETEM' && !x.is_system);
    const publicLibrary = libs.find(x => x.name === 'NETEM' && x.is_system);
    assert(privateLibrary && publicLibrary);
    const selection = await api('/api/lexicons/selection');
    check('existing explicit same-name private choice stays selected', selection.lexicon_id === privateLibrary.id && selection.source === 'explicit');
    const privateQueue = await api('/api/study/today');
    const privateWord = privateQueue.words.find(x => x.word === 'the'); assert(privateWord);
    check('private same-name definition and progress unchanged', privateWord.source_meanings.includes('副本自导同词释义') && privateWord.recall_success === 2);
    await page.goto(url + '/study');
    await page.getByRole('button', { name: /显示答案/ }).click();
    check('private study remains user supplied', (await body(page)).includes('用户提供的释义 · 未核实'));
    await page.goto(url + '/lexicons');
    await api('/api/lexicons/' + publicLibrary.id + '/select', {});
    await page.goto(url + '/study');
    await page.getByRole('button', { name: /显示答案/ }).click();
    await page.getByRole('heading', { name: 'the', exact: true }).waitFor();
    check('NETEM starts in original order', await page.getByRole('heading', { name: 'the', exact: true }).isVisible());
    check('default study compact attribution only', (await body(page)).includes('词典释义 · WikDict · 来源与许可') && !(await body(page)).includes('Karl Bartel') && await page.getByRole('dialog').count() === 0);
    await shot(page, 'study-desktop');
    const trigger = page.getByRole('button', { name: '来源与许可', exact: true });
    await trigger.click();
    const dialog = page.getByRole('dialog', { name: '来源与许可' });
    check('one click opens details outside answer', await dialog.isVisible() && await page.locator('.study-source [role=dialog]').count() === 0);
    check('full attribution fixed SHA extraction and warning present', (await dialog.innerText()).includes('Karl Bartel') && (await dialog.innerText()).includes('未做全库逐词语义校订') && (await dialog.innerText()).includes('SHA-256') && (await dialog.innerText()).includes('原文位置'));
    check('licence link present', await dialog.locator('a[href="https://creativecommons.org/licenses/by-sa/4.0/"]').count() > 0);
    await page.keyboard.press('Escape');
    await trigger.press('Space');
    await dialog.waitFor();
    await dialog.getByRole('link', { name: 'WikDict 来源详情' }).click();
    await page.locator('.source-card details[open]').waitFor();
    check('source link opens the corresponding folded card', page.url().includes('/sources#source-' + publicLibrary.id + '-') && (await body(page)).includes('Karl Bartel'));
    await page.goto(url + '/sources');
    await page.locator('.source-card').nth(2).waitFor();
    check('source details default folded', await page.locator('.source-card > details[open]').count() === 0);
    await page.locator('.source-card > details > summary').nth(1).click();
    check('source detail expands once with full extraction', (await body(page)).includes('我们做了什么') && (await body(page)).includes('导入文件 SHA-256'));
    await shot(page, 'sources-desktop');
    const publicQueue = await api('/api/study/today');
    const publicWord = publicQueue.words[0];
    check('same spelling has independent state', publicWord.word_state_id !== privateWord.word_state_id);
    await api('/api/study/word-states/' + publicWord.word_state_id + '/review', { result: 'know' });
    const ownAfter = await api('/api/words/state/' + privateWord.word_state_id);
    const publicAfter = await api('/api/words/state/' + publicWord.word_state_id);
    check('public review cannot overwrite private progress', ownAfter.recall_success === 2 && publicAfter.status !== 'new');
    for (const [file, content] of [['own.txt', 'the\n'], ['own.csv', 'word,meaning\nthe,个人释义\n']]) {
      await page.goto(url + '/lexicons');
      await page.getByLabel('词库名称', { exact: true }).fill('Copy browser ' + file);
      await page.getByLabel('选择 TXT 或 CSV 文件', { exact: true }).setInputFiles({ name: file, mimeType: 'text/plain', buffer: Buffer.from(content) });
      await page.getByRole('button', { name: '确认导入 1 个单词' }).click();
      await page.getByRole('status').filter({ hasText: '已导入 1 个单词' }).waitFor();
      await page.locator('article').filter({ hasText: 'Copy browser ' + file }).getByRole('button', { name: '学习这个词库' }).click();
      await page.getByRole('button', { name: /显示答案/ }).click();
      const q = await api('/api/study/today');
      check(file + ' private self import regression', q.words[0].word_state_id !== publicWord.word_state_id && (await body(page)).includes(file.endsWith('csv') ? '个人释义' : '暂无可用释义'));
      await page.reload(); await page.getByRole('button', { name: /显示答案/ }).waitFor();
      check(file + ' active choice survives reload', (await api('/api/lexicons/selection')).lexicon_id === q.lexicon_id);
    }
    await api('/api/lexicons/' + privateLibrary.id + '/select', {});
    results.persistence = { privateLexicon: privateLibrary.id, privateState: privateWord.word_state_id, privateSuccess: ownAfter.recall_success, publicState: publicWord.word_state_id, publicSuccess: publicAfter.recall_success, publicStatus: publicAfter.status };
    const mobile = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const phone = await mobile.newPage();
    phone.on('pageerror', e => errors.push(e.message));
    phone.on('console', message => {
      if (['error', 'warning'].includes(message.type()) && !message.text().includes('401 (Unauthorized)')) errors.push(message.text());
    });
    await login(phone, 'netem_copy_default');
    const mobileSelection = await api('/api/lexicons/selection', undefined, mobile);
    check('unselected user recommended NETEM without saving active choice', mobileSelection.lexicon_id === publicLibrary.id && mobileSelection.source === 'recommended');
    await phone.goto(url + '/study');
    await phone.getByRole('button', { name: /显示答案/ }).click();
    await phone.getByRole('heading', { name: 'modern', exact: true }).waitFor();
    check('mobile actual Chinese source short name', (await body(phone)).includes('词典释义 · 中文维基词典 · 来源与许可') && !(await body(phone)).includes('中文维基词典贡献者'));
    check('mobile compact line no horizontal overflow', await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await shot(phone, 'study-mobile');
    await phone.getByRole('button', { name: '来源与许可', exact: true }).click();
    const chinese = phone.getByRole('dialog');
    check('Chinese fixed old revision and full credits accessible', await chinese.locator('a[href="https://zh.wiktionary.org/w/index.php?oldid=9893726"]').count() > 0 && (await chinese.innerText()).includes('中文维基词典贡献者'));
    check('mobile expanded details no horizontal overflow', await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await shot(phone, 'details-mobile');
    await chinese.getByRole('link', { name: '中文维基词典 来源详情' }).click();
    await phone.locator('.source-card details[open]').waitFor();
    check('mobile source link opens target card', (await body(phone)).includes('oldid') || await phone.locator('a[href*="oldid=8368252"]').count() > 0);
    await shot(phone, 'sources-mobile');
    const excluded = ['shortage','temporary','thoughtful','tribute','tonight','ashore','set','complex','bit','honor','inhabit','pitch','progressive','build','collect','locate','outward','operation'];
    for (const word of excluded) {
      const found = await api('/api/words?search=' + encodeURIComponent(word), undefined, mobile);
      const entry = found.words.find(x => x.word === word && x.lexicon_id === publicLibrary.id); assert(entry, word);
      const detail = await api('/api/words/state/' + entry.word_state_id, undefined, mobile);
      check(word + ' removed definition has no raw or alternate fallback', detail.source_meanings.length === 0 && (detail.concise_meanings || []).length === 0);
      await phone.goto(url + '/library/' + entry.word_state_id);
      await phone.getByRole('heading', { name: word, exact: true }).waitFor();
      check(word + ' empty in rendered entry', (await body(phone)).includes('暂无可用释义'));
    }
    await shot(phone, 'empty-mobile');
    check('private library inaccessible to other account', (await mobile.request.get(url + '/api/lexicons/' + privateLibrary.id)).status() === 404);
    const finalChoice = await api('/api/lexicons/selection', undefined, mobile);
    check('recommendation is still not an explicit selection', finalChoice.source === 'recommended');
    await mobile.close();
  }
  check('nonblank app page with no framework overlay', (await page.title()).includes('拾词') && (await body(page)).length > 100 && await page.locator('vite-error-overlay').count() === 0);
  check('no page errors', errors.length === 0);
  results.success = true; results.pageErrors = errors;
  fs.writeFileSync(path.join(output, 'browser-' + phase + '.json'), JSON.stringify(results, null, 2));
  await browser.close();
  console.log(JSON.stringify({ success: true, phase, checks: results.checks.length, screenshots: results.screenshots }, null, 2));
})().catch(async error => { console.error(error); if (browser) await browser.close(); process.exitCode = 1; });
